Created Login UI and Upgraded Cognito Auth to Amplify Gen 2
ubc-biztech/bt-web-v2 pull request #18
Opened 2024-07-04 02:10 UTC by bennypc

**Overview:**
- Transitioned from a very old version of Amplify to Amplify Gen 2 for modern and flexible authentication. (trying to implement auth with a 5 year old version of amplify genuinely wanted made me want to die)
- Integrated existing Cognito User Pool with the new Amplify setup.
- Built a new UI based on updated UX designs.

**Changes Made:**
1. **Installed Necessary Packages:**
   - `aws-amplify`
   - `@aws-amplify/auth`

2. **Configured Amplify:**
   - Created a new `amplify_outputs.js` with existing Cognito User Pool details.
   - Protected via gitignore, will send to config file to devs soon

3. **Built New Login Component:**
   - Built a new login UI based on updated UX designs.
   - Improved user experience with modern styling and responsive design.

4. **Updated Auth Flow and Error Handling:**
   - Implemented validation and error handling for email and password.

**Summary:**
- Upgraded authentication to Amplify Gen 2.
- Integrated existing Cognito User Pool.
- Implemented new UI based on UX designs.

2024-07-04 04:16 UTC, voctory reviewed
Hey Benny, thanks for being proactive about getting the Amplify Gen 2 integration started! Really nice to hear that the existing Cognito User Pool should be compatible too

I've left some comments directly on the files, but some other things:
- Would it be possible to share a short video of logging into an existing account? To get a sense of the UI and the login latency
- Is the login UI mobile responsive?
- Could we change the PR's merge target branch to `dev`?
- If it's possible, I'd like to see the Vercel build fixed before we merge so that future PRs avoid automatically failing their Vercel builds

2024-07-08 15:00 UTC, AllanT102 commented
@bennypc fix this build by adding the necessary json configs to the pipeline so we can preview. otherwise looks good, you'll be handling the entire login flow and etc.

2024-07-09 01:09 UTC, bennypc commented on src/pages/login.tsx
> +                  src='https://i.ibb.co/0VtyXLD/Frame-3.png'
yeah sorry this was a rough implementation will replace with more image direct sources in the future

2024-07-09 01:10 UTC, bennypc commented on src/styles/globals.css
these are auto-generated styles created with the create-next-app; we have our own styles defined already

2024-07-09 01:10 UTC, bennypc commented on amplify/data/resource.ts
> +  Todo: a
yeah i'll be doing all tasks related to auth/amplify

2024-07-18 00:04 UTC, AllanT102 approved these changes

2024-07-18 00:22 UTC, AllanT102 commented
@bennypc good to merge once you fix merge conflicts. merge into dev pls

2024-07-24 00:53 UTC, voctory commented on src/pages/login.tsx
> +                  src='https://i.ibb.co/0VtyXLD/Frame-3.png'
Ok, please add this to the backlog too so we can keep track of it

2024-07-24 01:01 UTC, voctory requested changes
Left a comment on login error handling, will approve once it's addressed

2024-07-25 20:26 UTC, kevinxiao27 commented on src/pages/login.tsx
> +        console.error('Error signing in', error);
According to the current amplify auth [docs](https://docs.amplify.aws/gen1/javascript/build-a-backend/auth/enable-sign-up/) the user we resolve from the promise should have an isSignedIn field I believe is what we would use to determine if the sign-in was successful (I don't think nextsteps is relevant to what we're using for auth?). 

<img width="772" alt="image" src="https://github.com/user-attachments/assets/e65b4b15-1242-400f-a6ef-cfe5ae0bff55">

Conversely if we [getCurrentUser](https://docs.amplify.aws/react/build-a-backend/auth/connect-your-frontend/manage-user-sessions/), there will be an error thrown for unauthenticated users if we want to handle it that way.

2024-07-25 20:33 UTC, kevinxiao27 reviewed
I just left a comment about how signIn is handled using error catching from getCurrentUser or if we want to destructure the resolved signIn into {isSignedIn, nextSteps}. Like how victor writes, the component currently doesn't convey any information to the user about a failed signIn.

Not completely sure but we could merge dev into this branch so we can use next.js's <Image> and the logo from within the repo so its not stuck in the backlog

2024-07-26 05:12 UTC, voctory commented on src/pages/login.tsx
> +        console.error('Error signing in', error);
Thanks for the follow-up Kevin - the Amplify documentation doesn't make this very clear, but a failed `signIn` invocation throws an error according to the Amplify library's source code. So we wouldn't be able to use `isSignedIn` to check if a sign-in is successful since we would have gone to the catch block. `getCurrentUser` is a good thing to use when a user should already be logged in, but I don't think we need it here since we already have the error being thrown by `signIn`

Some sources:
- Relevant discussion on Stack Overflow, would recommend looking at Ben Weber's switch-case solution: https://stackoverflow.com/questions/65160061/aws-amplify-auth-errors
- The AWS Amplify library, signIn method propagates the error thrown by Cognito: https://github.com/aws-amplify/amplify-js/blob/main/packages/auth/src/providers/cognito/apis/signIn.ts#L23

2024-07-26 08:35 UTC, bennypc commented on src/pages/login.tsx
> +              src='https://i.ibb.co/s11md5S/Biztech-Logo-1.png'
Yeah I'll replace with the logo on the branch after merge

2024-07-29 00:43 UTC, voctory approved these changes

2024-07-30 06:45 UTC, merged